// File generated by FlutterFire CLI.
// This file is used to configure Firebase for the Flutter app.
// For the time being, we're using placeholder values to prevent initialization errors.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Real web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-KhJGJuxO_OBJYIhPYIv2xpNwV4V27Y',
    appId: '1:893517562971:web:f2664b1845cf48a96c957a',
    messagingSenderId: '893517562971',
    projectId: 'collaborative-whiteboard-flutter',
    authDomain: 'collaborative-whiteboard-flutter.firebaseapp.com',
    storageBucket: 'collaborative-whiteboard-flutter.appspot.com',
    measurementId: 'G-LMZGCQN3LD',
  );

  // Real Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNTMUSklzCGI_cpgHyFOXAORInIeQkUc',
    appId: '1:893517562971:android:8ae3c515830f9ba66c957a',
    messagingSenderId: '893517562971',
    projectId: 'collaborative-whiteboard-flutter',
    storageBucket: 'collaborative-whiteboard-flutter.appspot.com',
  );

  // Real iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLmNIB9vXaA9KchNnzLvZz_Ic-fPhhGY',
    appId: '1:893517562971:ios:5e831c52f8e1d5126c957a',
    messagingSenderId: '893517562971',
    projectId: 'collaborative-whiteboard-flutter',
    storageBucket: 'collaborative-whiteboard-flutter.appspot.com',
    iosClientId: '893517562971-ddcev5dnp9flp251u25j5119j9ao0vqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.collaborativeWhiteboard',
  );

  // Real macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLmNIB9vXaA9KchNnzLvZz_Ic-fPhhGY',
    appId: '1:893517562971:ios:5e831c52f8e1d5126c957a',
    messagingSenderId: '893517562971',
    projectId: 'collaborative-whiteboard-flutter',
    storageBucket: 'collaborative-whiteboard-flutter.appspot.com',
    iosClientId: '893517562971-ddcev5dnp9flp251u25j5119j9ao0vqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.collaborativeWhiteboard',
  );

  // Real Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE-KhJGJuxO_OBJYIhPYIv2xpNwV4V27Y',
    appId: '1:893517562971:web:f2664b1845cf48a96c957a',
    messagingSenderId: '893517562971',
    projectId: 'collaborative-whiteboard-flutter',
    authDomain: 'collaborative-whiteboard-flutter.firebaseapp.com',
    storageBucket: 'collaborative-whiteboard-flutter.appspot.com',
  );
}